export const chainConfigs = [
	{
		value: "sepolia",
		label: "Sepolia",
		name: "Sepolia",
		chainId: 11155111,
		network: "sepolia",
		rpc: "https://eth-sepolia.g.alchemy.com/v2/kjHIh07O7c7Od-1LLJ9Pv",
		wss: "wss://eth-sepolia.g.alchemy.com/v2/kjHIh07O7c7Od-1LLJ9Pv",
		blockExplorerUrls: ["https://sepolia.etherscan.io"],
		nativeCurrency: {
			name: "ETH",
			symbol: "SepoliaETH",
			decimals: 18,
		},
	},
	{
		value: "polygon",
		label: "Polygon Amoy",
		name: "Polygon",
		chainId: 80002,
		network: "polygon",
		rpc: "https://polygon-amoy.infura.io/v3/4213210e52fd4c4bba5138978d5966cf",
		wss: "wss://polygon-amoy.infura.io/ws/v3/4213210e52fd4c4bba5138978d5966cf",
		blockExplorerUrls: ["https://oklink.com/amoy"],
		nativeCurrency: {
			name: "POL",
			symbol: "POL",
			decimals: 18,
		},
	},
	{
		value: "binance",
		label: "BNB Smart Chain",
		name: "Binance",
		chainId: 97,
		network: "binance",
		rpc: "https://bsc-testnet.infura.io/v3/4213210e52fd4c4bba5138978d5966cf",
		blockExplorerUrls: ["https://testnet.bscscan.com"],
		nativeCurrency: {
			name: "TBNB",
			symbol: "TBNB",
			decimals: 18,
		},
	},
];
